// Code generated by make generate-oci-parity; DO NOT EDIT.

package fn

import "github.com/urfave/cli"

func GeneratedOCIParityCreateUpdateFnFlags() []cli.Flag {
	return []cli.Flag{
		cli.IntFlag{Name: "detached-mode-timeout-in-seconds", Usage: "Timeout for detached function invocations. Value in seconds."},
		cli.StringFlag{Name: "failure-destination", Usage: "OCI parity advanced option"},
		cli.StringFlag{Name: "success-destination", Usage: "OCI parity advanced option"},
		cli.IntFlag{Name: "timeout-in-seconds", Usage: "Timeout for executions of the function. Value in seconds."},
		cli.StringFlag{Name: "trace-config", Usage: "OCI parity advanced option"},
	}
}

func GeneratedOCIParityListFnFlags() []cli.Flag {
	return []cli.Flag{
		cli.StringFlag{Name: "display-name", Usage: "Filter functions by exact display name"},
		cli.StringFlag{Name: "id", Usage: "Filter functions by OCID"},
		cli.StringFlag{Name: "lifecycle-state", Usage: "Filter functions by lifecycle state"},
		cli.StringFlag{Name: "sort-by", Usage: "Sort functions by a supported field"},
		cli.StringFlag{Name: "sort-order", Usage: "Sort order for list results"},
	}
}
