// Code generated by make generate-oci-parity; DO NOT EDIT.

package fn

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	models "github.com/fnproject/fn_go/modelsv2"
	"github.com/urfave/cli"
)

const (
	annotationOCIParityFnDetachedModeTimeoutInSeconds = "oracle.com/oci/parity/detachedModeTimeoutInSeconds"
	annotationOCIParityFnFailureDestination = "oracle.com/oci/parity/failureDestination"
	annotationOCIParityFnSuccessDestination = "oracle.com/oci/parity/successDestination"
	annotationOCIParityFnTraceConfig = "oracle.com/oci/parity/traceConfig"
)

func readGeneratedOCIParityFnJSONInput(value string) (map[string]interface{}, error) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return nil, nil
	}
	if strings.HasPrefix(trimmed, "file://") {
		data, err := os.ReadFile(strings.TrimPrefix(trimmed, "file://"))
		if err != nil {
			return nil, err
		}
		trimmed = string(data)
	}
	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(trimmed), &parsed); err != nil {
		return nil, fmt.Errorf("invalid OCI parity JSON input: %w", err)
	}
	return parsed, nil
}

func ApplyGeneratedOCIParityFnFlags(c *cli.Context, fn *models.Fn) error {
	if fn.Annotations == nil {
		fn.Annotations = make(map[string]interface{})
	}
	if c.IsSet("detached-mode-timeout-in-seconds") {
		fn.Annotations[annotationOCIParityFnDetachedModeTimeoutInSeconds] = c.Int("detached-mode-timeout-in-seconds")
	}
	if c.IsSet("failure-destination") {
		parsed, err := readGeneratedOCIParityFnJSONInput(c.String("failure-destination"))
		if err != nil { return err }
		fn.Annotations[annotationOCIParityFnFailureDestination] = parsed
	}
	if c.IsSet("success-destination") {
		parsed, err := readGeneratedOCIParityFnJSONInput(c.String("success-destination"))
		if err != nil { return err }
		fn.Annotations[annotationOCIParityFnSuccessDestination] = parsed
	}
	if c.IsSet("timeout-in-seconds") {
		v := int32(c.Int("timeout-in-seconds"))
		fn.Timeout = &v
	}
	if c.IsSet("trace-config") {
		parsed, err := readGeneratedOCIParityFnJSONInput(c.String("trace-config"))
		if err != nil { return err }
		fn.Annotations[annotationOCIParityFnTraceConfig] = parsed
	}
	return nil
}
