version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    working_directory: ~/go/src/github.com/fnproject/cli
    environment: # apparently expansion doesn't work here yet: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
      - GO111MODULE=on
      - GOFLAGS=-mod=vendor
      - GOPATH=/home/circleci/go
      - GOVERSION=1.17
      - OS=linux
      - ARCH=amd64
      - DOCKER_VERSION=5:26.1.4-1~ubuntu.20.04~focal
    steps:
      - checkout
      # update Go
      - run: |
          go version
          go env GOROOT
          mkdir tmp
          cd tmp
          sudo rm -rf /usr/local/go
          wget https://dl.google.com/go/go$GOVERSION.$OS-$ARCH.tar.gz
          sudo tar -C /usr/local -xzf go$GOVERSION.$OS-$ARCH.tar.gz
          export PATH=$PATH:$HOME/go/bin
      - run: go version
      # update Docker
      - run: |
          docker version
          sudo service docker stop
          sudo apt-get update
          sudo apt-get install ca-certificates
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install --allow-downgrades docker-ce=$DOCKER_VERSION docker-ce-cli=$DOCKER_VERSION
      - run: docker version
      - run:
          name: build and test
          command: make test
          no_output_timeout: 20m
          environment:
      - run:
          name: test build macos
          command: go build -o fn_mac
          environment:
            GOOS: darwin
      - run:
          name: test build windows
          command: go build -o fn.exe
          environment:
            GOOS: windows
      - run:
          name: test build docker
          command: docker build -t fnproject/fn:latest .
      - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_PR_REPONAME}" ]]; then
              printenv DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              git config --global user.email "ci@fnproject.com"
              git config --global user.name "CI"
              git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
              ./release.sh
            fi
