// Code generated by make generate-oci-parity; DO NOT EDIT.

package app

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/fnproject/fn_go/modelsv2"
	"github.com/urfave/cli"
)

const (
	annotationOCIParityImagePolicyConfig = "oracle.com/oci/parity/imagePolicyConfig"
	annotationOCIParityNetworkSecurityGroupIds = "oracle.com/oci/parity/networkSecurityGroupIds"
	annotationOCIParitySecurityAttributes = "oracle.com/oci/parity/securityAttributes"
	annotationOCIParityTraceConfig = "oracle.com/oci/parity/traceConfig"
)

func readGeneratedOCIParityJSONInput(value string) (map[string]interface{}, error) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return nil, nil
	}
	if strings.HasPrefix(trimmed, "file://") {
		data, err := os.ReadFile(strings.TrimPrefix(trimmed, "file://"))
		if err != nil {
			return nil, err
		}
		trimmed = string(data)
	}
	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(trimmed), &parsed); err != nil {
		return nil, fmt.Errorf("invalid OCI parity JSON input: %w", err)
	}
	return parsed, nil
}

func ApplyGeneratedOCIParityAppFlags(c *cli.Context, app *modelsv2.App) error {
	if app.Annotations == nil {
		app.Annotations = make(map[string]interface{})
	}
	if c.IsSet("image-policy-config") {
		parsed, err := readGeneratedOCIParityJSONInput(c.String("image-policy-config"))
		if err != nil {
			return err
		}
		app.Annotations[annotationOCIParityImagePolicyConfig] = parsed
	}
	if len(c.StringSlice("network-security-group-ids")) > 0 {
		values := make([]interface{}, 0, len(c.StringSlice("network-security-group-ids")))
		for _, v := range c.StringSlice("network-security-group-ids") {
			values = append(values, strings.TrimSpace(v))
		}
		app.Annotations[annotationOCIParityNetworkSecurityGroupIds] = values
	}
	if c.IsSet("security-attributes") {
		parsed, err := readGeneratedOCIParityJSONInput(c.String("security-attributes"))
		if err != nil {
			return err
		}
		app.Annotations[annotationOCIParitySecurityAttributes] = parsed
	}
	if c.IsSet("trace-config") {
		parsed, err := readGeneratedOCIParityJSONInput(c.String("trace-config"))
		if err != nil {
			return err
		}
		app.Annotations[annotationOCIParityTraceConfig] = parsed
	}
	return nil
}
