// Code generated by make generate-oci-parity; DO NOT EDIT.

package app

import "github.com/urfave/cli"

func GeneratedOCIParityCreateUpdateAppFlags() []cli.Flag {
	return []cli.Flag{
		cli.StringFlag{Name: "image-policy-config", Usage: "OCI parity advanced option"},
		cli.StringSliceFlag{Name: "network-security-group-ids", Usage: "The [OCID](/iaas/Content/General/Concepts/identifiers.htm)s of the Network Security Groups to add the application to."},
		cli.StringFlag{Name: "security-attributes", Usage: "Security attributes for this resource. Each key is predefined and scoped to a namespace.\nFor more information, see [Resource Tags](/iaas/Content/General/Concepts/resourcetags.htm).\n\nExample: `{\"Oracle-ZPR\": {\"MaxEgressCount\": {\"value\": \"42\", \"mode\": \"enforce\"}}}`"},
		cli.StringFlag{Name: "trace-config", Usage: "OCI parity advanced option"},
	}
}

func GeneratedOCIParityListAppFlags() []cli.Flag {
	return []cli.Flag{
		cli.StringFlag{Name: "display-name", Usage: "Filter applications by exact display name"},
		cli.StringFlag{Name: "id", Usage: "Filter applications by OCID"},
		cli.StringFlag{Name: "lifecycle-state", Usage: "Filter applications by lifecycle state"},
		cli.StringFlag{Name: "sort-by", Usage: "Sort applications by a supported field"},
		cli.StringFlag{Name: "sort-order", Usage: "Sort order for list results"},
	}
}
