// Code generated by make generate-oci-parity; DO NOT EDIT.

package app

import (
	"strings"

	apiapps "github.com/fnproject/fn_go/clientv2/apps"
	"github.com/urfave/cli"
)

func ApplyGeneratedOCIParityAppListParams(c *cli.Context, params *apiapps.ListAppsParams) {
	if c.IsSet("display-name") {
		value := strings.TrimSpace(c.String("display-name"))
		if value != "" {
			params.DisplayName = &value
		}
	}
	if c.IsSet("id") {
		value := strings.TrimSpace(c.String("id"))
		if value != "" {
			params.ID = &value
		}
	}
	if c.IsSet("lifecycle-state") {
		value := strings.TrimSpace(c.String("lifecycle-state"))
		if value != "" {
			params.LifecycleState = &value
		}
	}
	if c.IsSet("sort-by") {
		value := strings.TrimSpace(c.String("sort-by"))
		if value != "" {
			params.SortBy = &value
		}
	}
	if c.IsSet("sort-order") {
		value := strings.TrimSpace(c.String("sort-order"))
		if value != "" {
			params.SortOrder = &value
		}
	}
}
