package ociparity

import (
	"fmt"
	"strings"
)

func renderHeader() string {
	return "// Code generated by make generate-oci-parity; DO NOT EDIT.\n\n"
}

func renderAppFlags(model *AppGenerationModel) string {
	var b strings.Builder
	b.WriteString(renderHeader())
	b.WriteString("package app\n\nimport \"github.com/urfave/cli\"\n\n")
	b.WriteString("func GeneratedOCIParityCreateUpdateAppFlags() []cli.Flag {\n\treturn []cli.Flag{\n")
	for _, f := range model.CreateUpdateFields {
		switch f.Kind {
		case "json":
			fmt.Fprintf(&b, "\t\tcli.StringFlag{Name: %q, Usage: %q},\n", f.FlagName, fallbackDescription(f, "OCI parity advanced option"))
		case "string-slice":
			fmt.Fprintf(&b, "\t\tcli.StringSliceFlag{Name: %q, Usage: %q},\n", f.FlagName, fallbackDescription(f, "OCI parity advanced option"))
		}
	}
	b.WriteString("\t}\n}\n\n")
	b.WriteString("func GeneratedOCIParityListAppFlags() []cli.Flag {\n\treturn []cli.Flag{\n")
	for _, f := range model.ListFields {
		fmt.Fprintf(&b, "\t\tcli.StringFlag{Name: %q, Usage: %q},\n", f.FlagName, fallbackDescription(f, "OCI parity list option"))
	}
	b.WriteString("\t}\n}\n")
	return b.String()
}

func renderAppApply(model *AppGenerationModel) string {
	var b strings.Builder
	b.WriteString(renderHeader())
	b.WriteString("package app\n\nimport (\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"os\"\n\t\"strings\"\n\n\t\"github.com/fnproject/fn_go/modelsv2\"\n\t\"github.com/urfave/cli\"\n)\n\n")
	b.WriteString("const (\n")
	for _, f := range model.CreateUpdateFields {
		fmt.Fprintf(&b, "\tannotationOCIParity%s = %q\n", exportName(f.Property), "oracle.com/oci/parity/"+f.Property)
	}
	b.WriteString(")\n\n")
	b.WriteString(`func readGeneratedOCIParityJSONInput(value string) (map[string]interface{}, error) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return nil, nil
	}
	if strings.HasPrefix(trimmed, "file://") {
		data, err := os.ReadFile(strings.TrimPrefix(trimmed, "file://"))
		if err != nil {
			return nil, err
		}
		trimmed = string(data)
	}
	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(trimmed), &parsed); err != nil {
		return nil, fmt.Errorf("invalid OCI parity JSON input: %w", err)
	}
	return parsed, nil
}

func ApplyGeneratedOCIParityAppFlags(c *cli.Context, app *modelsv2.App) error {
	if app.Annotations == nil {
		app.Annotations = make(map[string]interface{})
	}
`)
	for _, f := range model.CreateUpdateFields {
		switch f.Kind {
		case "json":
			fmt.Fprintf(&b, "\tif c.IsSet(%q) {\n\t\tparsed, err := readGeneratedOCIParityJSONInput(c.String(%q))\n\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n\t\tapp.Annotations[annotationOCIParity%s] = parsed\n\t}\n", f.FlagName, f.FlagName, exportName(f.Property))
		case "string-slice":
			fmt.Fprintf(&b, "\tif len(c.StringSlice(%q)) > 0 {\n\t\tvalues := make([]interface{}, 0, len(c.StringSlice(%q)))\n\t\tfor _, v := range c.StringSlice(%q) {\n\t\t\tvalues = append(values, strings.TrimSpace(v))\n\t\t}\n\t\tapp.Annotations[annotationOCIParity%s] = values\n\t}\n", f.FlagName, f.FlagName, f.FlagName, exportName(f.Property))
		}
	}
	b.WriteString("\treturn nil\n}\n")
	return b.String()
}

func renderAppList(model *AppGenerationModel) string {
	var b strings.Builder
	b.WriteString(renderHeader())
	b.WriteString("package app\n\nimport (\n\t\"strings\"\n\n\tapiapps \"github.com/fnproject/fn_go/clientv2/apps\"\n\t\"github.com/urfave/cli\"\n)\n\n")
	b.WriteString("func ApplyGeneratedOCIParityAppListParams(c *cli.Context, params *apiapps.ListAppsParams) {\n")
	for _, f := range model.ListFields {
		fmt.Fprintf(&b, "\tif c.IsSet(%q) {\n\t\tvalue := strings.TrimSpace(c.String(%q))\n\t\tif value != \"\" {\n", f.FlagName, f.FlagName)
		switch f.Property {
		case "displayName":
			b.WriteString("\t\t\tparams.DisplayName = &value\n")
		case "id":
			b.WriteString("\t\t\tparams.ID = &value\n")
		case "lifecycleState":
			b.WriteString("\t\t\tparams.LifecycleState = &value\n")
		case "sortBy":
			b.WriteString("\t\t\tparams.SortBy = &value\n")
		case "sortOrder":
			b.WriteString("\t\t\tparams.SortOrder = &value\n")
		}
		b.WriteString("\t\t}\n\t}\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func renderAppShim(model *AppGenerationModel) string {
	var b strings.Builder
	b.WriteString(renderHeader())
	b.WriteString("package shim\n\nimport (\n\t\"encoding/json\"\n\t\"fmt\"\n\n\t\"github.com/oracle/oci-go-sdk/v65/functions\"\n)\n\n")
	b.WriteString("const (\n")
	for _, f := range model.CreateUpdateFields {
		fmt.Fprintf(&b, "\tannotationOCIParity%s = %q\n", exportName(f.Property), "oracle.com/oci/parity/"+f.Property)
	}
	b.WriteString(")\n\n")
	b.WriteString("func applyGeneratedOCIParityCreateApplicationDetails(details *functions.CreateApplicationDetails, annotations map[string]interface{}) error {\n")
	b.WriteString(renderAppShimBody(model))
	b.WriteString("\treturn nil\n}\n\n")
	b.WriteString("func applyGeneratedOCIParityUpdateApplicationDetails(details *functions.UpdateApplicationDetails, annotations map[string]interface{}) error {\n")
	b.WriteString(renderAppShimBody(model))
	b.WriteString("\treturn nil\n}\n\n")
	b.WriteString(`func applyGeneratedOCIParityListApplicationsRequest(params interface{ GetDisplayName() *string; GetID() *string; GetLifecycleState() *string; GetSortBy() *string; GetSortOrder() *string }, req *functions.ListApplicationsRequest) {
	if params.GetDisplayName() != nil { req.DisplayName = params.GetDisplayName() }
	if params.GetID() != nil { req.Id = params.GetID() }
	if params.GetLifecycleState() != nil { req.LifecycleState = functions.ApplicationLifecycleStateEnum(*params.GetLifecycleState()) }
	if params.GetSortBy() != nil { req.SortBy = functions.ListApplicationsSortByEnum(*params.GetSortBy()) }
	if params.GetSortOrder() != nil { req.SortOrder = functions.ListApplicationsSortOrderEnum(*params.GetSortOrder()) }
}
`)
	return b.String()
}

func renderAppShimBody(model *AppGenerationModel) string {
	var b strings.Builder
	for _, f := range model.CreateUpdateFields {
		constName := "annotationOCIParity" + exportName(f.Property)
		switch f.Property {
		case "traceConfig":
			fmt.Fprintf(&b, "\tif raw, ok := annotations[%s]; ok {\n\t\tdata, err := json.Marshal(raw)\n\t\tif err != nil { return err }\n\t\tvar parsed functions.ApplicationTraceConfig\n\t\tif err := json.Unmarshal(data, &parsed); err != nil { return fmt.Errorf(\"invalid traceConfig parity annotation: %%w\", err) }\n\t\tdetails.TraceConfig = &parsed\n\t}\n", constName)
		case "imagePolicyConfig":
			fmt.Fprintf(&b, "\tif raw, ok := annotations[%s]; ok {\n\t\tdata, err := json.Marshal(raw)\n\t\tif err != nil { return err }\n\t\tvar parsed functions.ImagePolicyConfig\n\t\tif err := json.Unmarshal(data, &parsed); err != nil { return fmt.Errorf(\"invalid imagePolicyConfig parity annotation: %%w\", err) }\n\t\tdetails.ImagePolicyConfig = &parsed\n\t}\n", constName)
		case "securityAttributes":
			fmt.Fprintf(&b, "\tif raw, ok := annotations[%s]; ok {\n\t\tdata, err := json.Marshal(raw)\n\t\tif err != nil { return err }\n\t\tvar parsed map[string]map[string]interface{}\n\t\tif err := json.Unmarshal(data, &parsed); err != nil { return fmt.Errorf(\"invalid securityAttributes parity annotation: %%w\", err) }\n\t\tdetails.SecurityAttributes = parsed\n\t}\n", constName)
		case "networkSecurityGroupIds":
			fmt.Fprintf(&b, "\tif raw, ok := annotations[%s]; ok {\n\t\tvar ids []string\n\t\tswitch typed := raw.(type) {\n\t\tcase []interface{}:\n\t\t\tfor _, v := range typed { if s, ok := v.(string); ok { ids = append(ids, s) } }\n\t\tcase []string:\n\t\t\tids = append(ids, typed...)\n\t\tdefault:\n\t\t\treturn fmt.Errorf(\"invalid networkSecurityGroupIds parity annotation\")\n\t\t}\n\t\tdetails.NetworkSecurityGroupIds = ids\n\t}\n", constName)
		}
	}
	return b.String()
}

func renderFnFlags(model *FnGenerationModel) string {
	var b strings.Builder
	b.WriteString(renderHeader())
	b.WriteString("package fn\n\nimport \"github.com/urfave/cli\"\n\n")
	b.WriteString("func GeneratedOCIParityCreateUpdateFnFlags() []cli.Flag {\n\treturn []cli.Flag{\n")
	for _, f := range model.CreateUpdateFields {
		switch f.Kind {
		case "json":
			fmt.Fprintf(&b, "\t\tcli.StringFlag{Name: %q, Usage: %q},\n", f.FlagName, fallbackDescription(f, "OCI parity advanced option"))
		case "int":
			fmt.Fprintf(&b, "\t\tcli.IntFlag{Name: %q, Usage: %q},\n", f.FlagName, fallbackDescription(f, "OCI parity advanced option"))
		}
	}
	b.WriteString("\t}\n}\n\n")
	b.WriteString("func GeneratedOCIParityListFnFlags() []cli.Flag {\n\treturn []cli.Flag{\n")
	for _, f := range model.ListFields {
		fmt.Fprintf(&b, "\t\tcli.StringFlag{Name: %q, Usage: %q},\n", f.FlagName, fallbackDescription(f, "OCI parity list option"))
	}
	b.WriteString("\t}\n}\n")
	return b.String()
}

func renderFnApply(model *FnGenerationModel) string {
	var b strings.Builder
	b.WriteString(renderHeader())
	b.WriteString("package fn\n\nimport (\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"os\"\n\t\"strings\"\n\n\tmodels \"github.com/fnproject/fn_go/modelsv2\"\n\t\"github.com/urfave/cli\"\n)\n\n")
	b.WriteString("const (\n")
	for _, f := range model.CreateUpdateFields {
		if f.Property != "timeoutInSeconds" {
			fmt.Fprintf(&b, "\tannotationOCIParityFn%s = %q\n", exportName(f.Property), "oracle.com/oci/parity/"+f.Property)
		}
	}
	b.WriteString(")\n\n")
	b.WriteString(`func readGeneratedOCIParityFnJSONInput(value string) (map[string]interface{}, error) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return nil, nil
	}
	if strings.HasPrefix(trimmed, "file://") {
		data, err := os.ReadFile(strings.TrimPrefix(trimmed, "file://"))
		if err != nil {
			return nil, err
		}
		trimmed = string(data)
	}
	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(trimmed), &parsed); err != nil {
		return nil, fmt.Errorf("invalid OCI parity JSON input: %w", err)
	}
	return parsed, nil
}

func ApplyGeneratedOCIParityFnFlags(c *cli.Context, fn *models.Fn) error {
	if fn.Annotations == nil {
		fn.Annotations = make(map[string]interface{})
	}
`)
	for _, f := range model.CreateUpdateFields {
		switch f.Property {
		case "traceConfig":
			fmt.Fprintf(&b, "\tif c.IsSet(%q) {\n\t\tparsed, err := readGeneratedOCIParityFnJSONInput(c.String(%q))\n\t\tif err != nil { return err }\n\t\tfn.Annotations[annotationOCIParityFn%s] = parsed\n\t}\n", f.FlagName, f.FlagName, exportName(f.Property))
		case "timeoutInSeconds":
			fmt.Fprintf(&b, "\tif c.IsSet(%q) {\n\t\tv := int32(c.Int(%q))\n\t\tfn.Timeout = &v\n\t}\n", f.FlagName, f.FlagName)
		case "detachedModeTimeoutInSeconds":
			fmt.Fprintf(&b, "\tif c.IsSet(%q) {\n\t\tfn.Annotations[annotationOCIParityFn%s] = c.Int(%q)\n\t}\n", f.FlagName, exportName(f.Property), f.FlagName)
		case "successDestination", "failureDestination":
			fmt.Fprintf(&b, "\tif c.IsSet(%q) {\n\t\tparsed, err := readGeneratedOCIParityFnJSONInput(c.String(%q))\n\t\tif err != nil { return err }\n\t\tfn.Annotations[annotationOCIParityFn%s] = parsed\n\t}\n", f.FlagName, f.FlagName, exportName(f.Property))
		}
	}
	b.WriteString("\treturn nil\n}\n")
	return b.String()
}

func renderFnList(model *FnGenerationModel) string {
	var b strings.Builder
	b.WriteString(renderHeader())
	b.WriteString("package fn\n\nimport (\n\t\"strings\"\n\n\tapifns \"github.com/fnproject/fn_go/clientv2/fns\"\n\t\"github.com/urfave/cli\"\n)\n\n")
	b.WriteString("func ApplyGeneratedOCIParityFnListParams(c *cli.Context, params *apifns.ListFnsParams) {\n")
	for _, f := range model.ListFields {
		fmt.Fprintf(&b, "\tif c.IsSet(%q) {\n\t\tvalue := strings.TrimSpace(c.String(%q))\n\t\tif value != \"\" {\n", f.FlagName, f.FlagName)
		switch f.Property {
		case "displayName":
			b.WriteString("\t\t\tparams.DisplayName = &value\n")
		case "id":
			b.WriteString("\t\t\tparams.ID = &value\n")
		case "lifecycleState":
			b.WriteString("\t\t\tparams.LifecycleState = &value\n")
		case "sortBy":
			b.WriteString("\t\t\tparams.SortBy = &value\n")
		case "sortOrder":
			b.WriteString("\t\t\tparams.SortOrder = &value\n")
		}
		b.WriteString("\t\t}\n\t}\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func renderFnShim(model *FnGenerationModel) string {
	var b strings.Builder
	b.WriteString(renderHeader())
	b.WriteString("package shim\n\nimport (\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"strings\"\n\n\t\"github.com/oracle/oci-go-sdk/v65/functions\"\n)\n\n")
	b.WriteString("const (\n")
	for _, f := range model.CreateUpdateFields {
		if f.Property != "timeoutInSeconds" {
			fmt.Fprintf(&b, "\tannotationOCIParityFn%s = %q\n", exportName(f.Property), "oracle.com/oci/parity/"+f.Property)
		}
	}
	b.WriteString(")\n\n")
	b.WriteString(`func parseGeneratedSuccessDestination(raw interface{}) (functions.SuccessDestinationDetails, error) {
	data, err := json.Marshal(raw)
	if err != nil { return nil, err }
	var kindHolder map[string]interface{}
	if err := json.Unmarshal(data, &kindHolder); err != nil { return nil, err }
	kind, _ := kindHolder["kind"].(string)
	kind = strings.ToUpper(strings.TrimSpace(kind))
	if kind == "NOTIFICATIONS" {
		kind = "NOTIFICATION"
		kindHolder["kind"] = kind
		data, err = json.Marshal(kindHolder)
		if err != nil { return nil, err }
	}
	switch kind {
	case "STREAM":
		var parsed functions.StreamSuccessDestinationDetails
		if err := json.Unmarshal(data, &parsed); err != nil { return nil, err }
		return parsed, nil
	case "QUEUE":
		var parsed functions.QueueSuccessDestinationDetails
		if err := json.Unmarshal(data, &parsed); err != nil { return nil, err }
		return parsed, nil
	case "NOTIFICATION":
		var parsed functions.NotificationSuccessDestinationDetails
		if err := json.Unmarshal(data, &parsed); err != nil { return nil, err }
		return parsed, nil
	case "NONE":
		var parsed functions.NoneSuccessDestinationDetails
		if err := json.Unmarshal(data, &parsed); err != nil { return nil, err }
		return parsed, nil
	default:
		return nil, fmt.Errorf("invalid successDestination parity annotation kind %q", kind)
	}
}

func parseGeneratedFailureDestination(raw interface{}) (functions.FailureDestinationDetails, error) {
	data, err := json.Marshal(raw)
	if err != nil { return nil, err }
	var kindHolder map[string]interface{}
	if err := json.Unmarshal(data, &kindHolder); err != nil { return nil, err }
	kind, _ := kindHolder["kind"].(string)
	kind = strings.ToUpper(strings.TrimSpace(kind))
	if kind == "NOTIFICATIONS" {
		kind = "NOTIFICATION"
		kindHolder["kind"] = kind
		data, err = json.Marshal(kindHolder)
		if err != nil { return nil, err }
	}
	switch kind {
	case "STREAM":
		var parsed functions.StreamFailureDestinationDetails
		if err := json.Unmarshal(data, &parsed); err != nil { return nil, err }
		return parsed, nil
	case "QUEUE":
		var parsed functions.QueueFailureDestinationDetails
		if err := json.Unmarshal(data, &parsed); err != nil { return nil, err }
		return parsed, nil
	case "NOTIFICATION":
		var parsed functions.NotificationFailureDestinationDetails
		if err := json.Unmarshal(data, &parsed); err != nil { return nil, err }
		return parsed, nil
	case "NONE":
		var parsed functions.NoneFailureDestinationDetails
		if err := json.Unmarshal(data, &parsed); err != nil { return nil, err }
		return parsed, nil
	default:
		return nil, fmt.Errorf("invalid failureDestination parity annotation kind %q", kind)
	}
}
`)
	b.WriteString("func applyGeneratedOCIParityCreateFunctionDetails(details *functions.CreateFunctionDetails, annotations map[string]interface{}) error {\n")
	b.WriteString(renderFnShimBody(model))
	b.WriteString("\treturn nil\n}\n\n")
	b.WriteString("func applyGeneratedOCIParityUpdateFunctionDetails(details *functions.UpdateFunctionDetails, annotations map[string]interface{}) error {\n")
	b.WriteString(renderFnShimBody(model))
	b.WriteString("\treturn nil\n}\n\n")
	b.WriteString(`func applyGeneratedOCIParityListFunctionsRequest(params interface{ GetDisplayName() *string; GetID() *string; GetLifecycleState() *string; GetSortBy() *string; GetSortOrder() *string }, req *functions.ListFunctionsRequest) {
	if params.GetDisplayName() != nil { req.DisplayName = params.GetDisplayName() }
	if params.GetID() != nil { req.Id = params.GetID() }
	if params.GetLifecycleState() != nil { req.LifecycleState = functions.FunctionLifecycleStateEnum(*params.GetLifecycleState()) }
	if params.GetSortBy() != nil { req.SortBy = functions.ListFunctionsSortByEnum(*params.GetSortBy()) }
	if params.GetSortOrder() != nil { req.SortOrder = functions.ListFunctionsSortOrderEnum(*params.GetSortOrder()) }
}
`)
	return b.String()
}

func renderFnShimBody(model *FnGenerationModel) string {
	var b strings.Builder
	for _, f := range model.CreateUpdateFields {
		switch f.Property {
		case "traceConfig":
			fmt.Fprintf(&b, "\tif raw, ok := annotations[annotationOCIParityFn%s]; ok {\n\t\tdata, err := json.Marshal(raw)\n\t\tif err != nil { return err }\n\t\tvar parsed functions.FunctionTraceConfig\n\t\tif err := json.Unmarshal(data, &parsed); err != nil { return fmt.Errorf(\"invalid traceConfig parity annotation: %%w\", err) }\n\t\tdetails.TraceConfig = &parsed\n\t}\n", exportName(f.Property))
		case "detachedModeTimeoutInSeconds":
			fmt.Fprintf(&b, "\tif raw, ok := annotations[annotationOCIParityFn%s]; ok {\n\t\tswitch typed := raw.(type) {\n\t\tcase int:\n\t\t\tv := typed\n\t\t\tdetails.DetachedModeTimeoutInSeconds = &v\n\t\tcase int32:\n\t\t\tv := int(typed)\n\t\t\tdetails.DetachedModeTimeoutInSeconds = &v\n\t\tcase int64:\n\t\t\tv := int(typed)\n\t\t\tdetails.DetachedModeTimeoutInSeconds = &v\n\t\tcase float64:\n\t\t\tv := int(typed)\n\t\t\tdetails.DetachedModeTimeoutInSeconds = &v\n\t\tdefault:\n\t\t\treturn fmt.Errorf(\"invalid detachedModeTimeoutInSeconds parity annotation\")\n\t\t}\n\t}\n", exportName(f.Property))
		case "successDestination":
			fmt.Fprintf(&b, "\tif raw, ok := annotations[annotationOCIParityFn%s]; ok {\n\t\tparsed, err := parseGeneratedSuccessDestination(raw)\n\t\tif err != nil { return fmt.Errorf(\"invalid successDestination parity annotation: %%w\", err) }\n\t\tdetails.SuccessDestination = parsed\n\t}\n", exportName(f.Property))
		case "failureDestination":
			fmt.Fprintf(&b, "\tif raw, ok := annotations[annotationOCIParityFn%s]; ok {\n\t\tparsed, err := parseGeneratedFailureDestination(raw)\n\t\tif err != nil { return fmt.Errorf(\"invalid failureDestination parity annotation: %%w\", err) }\n\t\tdetails.FailureDestination = parsed\n\t}\n", exportName(f.Property))
		}
	}
	return b.String()
}

func exportName(v string) string {
	if v == "" {
		return ""
	}
	return strings.ToUpper(v[:1]) + v[1:]
}

func fallbackDescription(f GeneratedField, fallback string) string {
	if strings.TrimSpace(f.Description) != "" {
		return f.Description
	}
	return fallback
}
